import { NextRequest, NextResponse } from "next/server";
import { currentUser } from "@clerk/nextjs/server";
import { prisma } from "@/lib/prisma";
import { resolveModelsForChat, incrementApiUsage, IncrementApiUsageParams } from "@/lib/modelSelection";
import { fetchRelevantData, DATA_TYPES } from "./datalabHelper";
import { callOpenAIChat, performAiReviewCycle, AiReviewCycleRawOutputs } from "@/lib/aiService";
import { ChatCompletionMessageParam, ChatCompletionSystemMessageParam } from "openai/resources/chat/completions";

const FALLBACK_DATALAB_CODER_SYSTEM_PROMPT_TEMPLATE = `
You are an AI assistant specialized in creating D3.js visualizations and exporting data for a citizen science gaming platform.
You have access to data from MongoDB and PostgreSQL based on the user's selection.

IMPORTANT: The data is ALREADY PROVIDED to you in the dataContext when you generate code.
DO NOT generate code that fetches data using d3.json() or any other external data fetching.
All data must be used from the \`dataContext\` variable which will be made available to your code.

General Available Data Overview:
The user can select from these data categories: %%DATALAB_AVAILABLE_DATA_CATEGORIES%%
A general set of keys that *might* be available in the dataContext (depending on selection and query) includes: %%DATALAB_GENERAL_SCHEMA_OVERVIEW%%

Query-Specific Data Context:
For the current user query, the exact available data keys in the \`dataContext\` are: %%DATALAB_QUERY_SPECIFIC_DATACONTEXT_KEYS%%
Use these specific keys to access data. For example: \`dataContext.recentSessions\`, \`dataContext.userSurveys['someKey']\`.
%%DATALAB_SANDBOX_FETCH_ERROR_NOTE%%

### Task: Visualization or Data Export

- **If the user asks for a plot, chart, or visualization:** Your task is to generate D3.js code to create a visual representation of the data.
- **If the user asks for a 'data set', 'raw data', or 'JSON':** Your task is to generate D3.js code that displays the raw data as a formatted JSON string.

### Instructions for D3.js Visualizations
When creating visualizations:
1. Generate pure D3.js code that can be executed in a browser.
2. The code should expect 'd3', 'container' (the HTML element for the chart), and 'dataContext' as parameters.
3. Use the container parameter as the target element for the visualization.
4. EMBED ALL DATA referenced FROM THE \`dataContext\` DIRECTLY IN THE CODE if needed, or use the \`dataContext\` variable directly.
5. Include proper scales, axes, and labels.
6. Use responsive design principles where possible.
7. Apply emerald colors (#10B981, #059669, #047857) to match the theme.
8. Handle edge cases like empty data gracefully (e.g., if \`dataContext.userSurveys\` is empty).

Example of how to structure your visualization code:
\`\`\`javascript
// Access data from the provided dataContext
const sessions = dataContext.recentSessions || []; 

if (dataContext.sandboxFetchError) {
  d3.select(container).append("p").style("color", "orange").text("Note: Sandbox data could not be fetched: " + dataContext.sandboxFetchError);
}

if (!sessions || sessions.length === 0) {
  d3.select(container)
    .append("p")
    .style("text-align", "center")
    .text("No session data available for visualization based on your selection.");
  return; // IMPORTANT: return early if no data to prevent errors
}

const margin = {top: 20, right: 30, bottom: 40, left: 90};
// ... rest of your D3 code ...
\`\`\`

### Instructions for Data Export
When a user asks for a dataset:
1. Analyze what data is relevant from the \`dataContext\` (keys: %%DATALAB_QUERY_SPECIFIC_DATACONTEXT_KEYS%%).
2. Generate D3 code that creates a \`<pre>\` element and displays the relevant data from \`dataContext\` as a formatted JSON string inside it.
3. Return ONLY the JavaScript code for this D3.js script.

Example for data export:
\`\`\`javascript
// Access the requested data from the dataContext
const dataToDisplay = dataContext.pointTransfers || [];

// Display the data as a JSON string in a <pre> tag
d3.select(container)
  .append('pre')
  .style('font-size', '12px')
  .style('text-align', 'left')
  .text(JSON.stringify(dataToDisplay, null, 2));
\`\`\`

Return ONLY the JavaScript code. Do not include explanations unless specifically asked.
`;

const FALLBACK_DATALAB_REVIEWER_SYSTEM_PROMPT = `
You are an AI expert in D3.js code and data visualization. Your task is to review D3.js code that was generated by another AI assistant.
The initial AI was given a user's query, a system prompt, and access to a \`dataContext\` object for data.
Focus your review on:
1.  **Correctness:** Does the code run without errors? Does it accurately represent the data?
2.  **Data Usage:** Does the code correctly and safely access data from the \`dataContext\` variable? (e.g., \`dataContext.recentSessions\`). It should NOT use \`d3.json()\` or other external data fetching methods.
3.  **D3 Best Practices:** Does the code follow D3.js conventions and best practices (e.g., proper use of selections, scales, axes, data binding)?
4.  **Efficiency:** Is the code reasonably efficient for the task?
5.  **Clarity and Readability:** Is the code well-structured and easy to understand?
6.  **Visualization Choices:** Is the chosen type of visualization appropriate for the data and the user's likely intent?
7.  **Aesthetics and Presentation:** Are labels, titles, and axes clear? Is the visual design (e.g., colors, layout) effective and appealing? (Emerald colors like #10B981 are preferred).
8.  **Error Handling:** Does the code handle potential issues like empty or malformed data in \`dataContext\` gracefully?

Provide constructive feedback. Be specific. If you find errors or areas for improvement, explain them and suggest concrete changes or alternatives.
Return only your review of the D3.js code.
`;

function getMonthlyLimitForTier(tier?: string | null): number {
  switch (tier) {
    case "premium":
      return 500;
    case "premium_plus":
      return 1500;
    default:
      return 100;
  }
}

function extractCodeFromResponse(aiResponseContent: string | null, defaultMessage: string = "AI response:"): { code: string; message_text: string } {
  if (!aiResponseContent) return { code: "", message_text: "No content from AI." };
  let code = "";
  let message_text = aiResponseContent;
  const codeMatch = aiResponseContent.match(/```(?:javascript|js)?\n([\s\S]*?)```/);
  if (codeMatch && codeMatch[1]) {
    code = codeMatch[1].trim();
    message_text = aiResponseContent.replace(/```(?:javascript|js)?\n[\s\S]*?```/, "").trim() || "Generated D3.js code.";
  } else if (aiResponseContent.includes("d3.select") && (aiResponseContent.includes("svg") || aiResponseContent.includes("container"))) {
    code = aiResponseContent;
    message_text = defaultMessage;
  }
  return { code, message_text };
}

export async function POST(request: NextRequest) {
  try {
    const clerkUser = await currentUser();
    if (!clerkUser || !clerkUser.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { 
        message: userQuery, 
        chatHistory, 
        coderSystemPrompt, // Renamed
        reviewerSystemPrompt, // New
        selectedDataTypes, 
        useCodeReview, 
        selectedCoderModelId, 
        selectedReviewerModelId 
    } = await request.json();

    const profile = await prisma.profile.findUnique({
        where: { userId: clerkUser.id },
        select: { subscriptionActive: true, subscriptionTier: true },
    });
    const isSubscribed = profile?.subscriptionActive || false;

    const querySpecificDataContext = await fetchRelevantData(userQuery, clerkUser.id, selectedDataTypes);
    const querySpecificContextKeys = Object.keys(querySpecificDataContext);
    const sandboxErrorNoteForPrompt = querySpecificDataContext.sandboxFetchError ? `Note: Sandbox data error: ${querySpecificDataContext.sandboxFetchError}` : '';

    let coderSystemPromptToUse: string;
    if (coderSystemPrompt && coderSystemPrompt.trim() !== "") {
      coderSystemPromptToUse = coderSystemPrompt
        .replace('%%DATALAB_QUERY_SPECIFIC_DATACONTEXT_KEYS%%', JSON.stringify(querySpecificContextKeys))
        .replace('%%DATALAB_SANDBOX_FETCH_ERROR_NOTE%%', sandboxErrorNoteForPrompt);
      if (coderSystemPromptToUse.includes('%%DATALAB_AVAILABLE_DATA_CATEGORIES%%') || coderSystemPromptToUse.includes('%%DATALAB_GENERAL_SCHEMA_OVERVIEW%%')) {
        const generalContext = await fetchRelevantData("general overview", clerkUser.id, Object.values(DATA_TYPES));
        coderSystemPromptToUse = coderSystemPromptToUse
          .replace('%%DATALAB_AVAILABLE_DATA_CATEGORIES%%', JSON.stringify(Object.values(DATA_TYPES)))
          .replace('%%DATALAB_GENERAL_SCHEMA_OVERVIEW%%', JSON.stringify(Object.keys(generalContext)));
      }
    } else {
      const generalContextForFallback = await fetchRelevantData("general overview", clerkUser.id, Object.values(DATA_TYPES));
      coderSystemPromptToUse = FALLBACK_DATALAB_CODER_SYSTEM_PROMPT_TEMPLATE
        .replace('%%DATALAB_AVAILABLE_DATA_CATEGORIES%%', JSON.stringify(Object.values(DATA_TYPES)))
        .replace('%%DATALAB_GENERAL_SCHEMA_OVERVIEW%%', JSON.stringify(Object.keys(generalContextForFallback)))
        .replace('%%DATALAB_QUERY_SPECIFIC_DATACONTEXT_KEYS%%', JSON.stringify(querySpecificContextKeys))
        .replace('%%DATALAB_SANDBOX_FETCH_ERROR_NOTE%%', sandboxErrorNoteForPrompt);
    }

    let reviewerSystemPromptToUse: string | null = null;
    if (useCodeReview) {
        let prompt: string;
        
        if (reviewerSystemPrompt && reviewerSystemPrompt.trim() !== "") {
            prompt = reviewerSystemPrompt
              .replace('%%DATALAB_QUERY_SPECIFIC_DATACONTEXT_KEYS%%', JSON.stringify(querySpecificContextKeys))
              .replace('%%DATALAB_SANDBOX_FETCH_ERROR_NOTE%%', sandboxErrorNoteForPrompt);
              
            if (prompt.includes('%%DATALAB_AVAILABLE_DATA_CATEGORIES%%') || prompt.includes('%%DATALAB_GENERAL_SCHEMA_OVERVIEW%%')) {
                const generalContext = await fetchRelevantData("general overview", clerkUser.id, Object.values(DATA_TYPES));
                prompt = prompt
                    .replace('%%DATALAB_AVAILABLE_DATA_CATEGORIES%%', JSON.stringify(Object.values(DATA_TYPES)))
                    .replace('%%DATALAB_GENERAL_SCHEMA_OVERVIEW%%', JSON.stringify(Object.keys(generalContext)));
            }
        } else {
            const generalContextForFallback = await fetchRelevantData("general overview", clerkUser.id, Object.values(DATA_TYPES));
            prompt = FALLBACK_DATALAB_REVIEWER_SYSTEM_PROMPT
                .replace('%%DATALAB_AVAILABLE_DATA_CATEGORIES%%', JSON.stringify(Object.values(DATA_TYPES)))
                .replace('%%DATALAB_GENERAL_SCHEMA_OVERVIEW%%', JSON.stringify(Object.keys(generalContextForFallback)))
                .replace('%%DATALAB_QUERY_SPECIFIC_DATACONTEXT_KEYS%%', JSON.stringify(querySpecificContextKeys))
                .replace('%%DATALAB_SANDBOX_FETCH_ERROR_NOTE%%', sandboxErrorNoteForPrompt);
        }
        
        reviewerSystemPromptToUse = prompt;
    }

    let finalApiResponse: { message: string; code?: string; dataContext?: any; remainingRequests?: number; error?: string; limitReached?: boolean };

    const initialUserMessages: ChatCompletionMessageParam[] = [
        ...(chatHistory.map((msg: any) => ({ role: msg.role, content: msg.content })) as ChatCompletionMessageParam[]),
        { role: "user", content: `Selected data types for this query: ${selectedDataTypes?.join(', ') || 'Default (Game Data)'}. User's request: ${userQuery}` }
    ];
    const coderSystemMessage: ChatCompletionSystemMessageParam = { role: "system", content: coderSystemPromptToUse };
    const reviewerSystemMessage: ChatCompletionSystemMessageParam | null = reviewerSystemPromptToUse ? { role: "system", content: reviewerSystemPromptToUse } : null;
    
    const modelResolution = await resolveModelsForChat(
        clerkUser.id, 
        isSubscribed, 
        useCodeReview, 
        selectedCoderModelId, 
        selectedReviewerModelId
    );

    if (!modelResolution.canUseApi || modelResolution.limitReached) {
      return NextResponse.json({
        error: modelResolution.error || "Monthly API request limit reached.",
        limitReached: true,
        dataContext: querySpecificDataContext
      }, { status: modelResolution.limitReached ? 403 : 400 });
    }
    if (modelResolution.error) {
        return NextResponse.json({ error: modelResolution.error, dataContext: querySpecificDataContext }, { status: 400 });
    }

    if (useCodeReview) {
      if (!modelResolution.chatbot1Model || !modelResolution.chatbot2Model) {
        console.error("DataLab API: Code review models not resolved properly for user", clerkUser.id);
        return NextResponse.json({ error: "Failed to resolve models for code review.", dataContext: querySpecificDataContext }, { status: 500 });
      }
      const chatbot1ModelToUse = modelResolution.chatbot1Model;
      const chatbot2ModelToUse = modelResolution.chatbot2Model;

      // The user message to the reviewer includes the coder's system prompt for context
      const createReviewerPrompt = (initialGenerationContent: string | null): string => `
You are reviewing D3.js code. Below is the original user request, the system prompt given to the AI that generated the code, and the code itself.
The data for the visualization is expected to be in a \`dataContext\` variable.
Your task is to provide a critical review based on the system prompt you (the reviewer) received separately.

Original User Request to Initial AI (Chatbot1):
---
Selected data types for this query: ${selectedDataTypes?.join(', ') || 'Default (Game Data)'}. User's request: ${userQuery}
---
System Prompt used for Initial AI (Chatbot1):
---
${coderSystemPromptToUse}
---
D3.js Code generated by Initial AI (Chatbot1):
---
\`\`\`javascript
${extractCodeFromResponse(initialGenerationContent).code || "Chatbot1 did not produce reviewable code."}
\`\`\`
---
Your review of the D3.js code (focus on correctness, data usage from \`dataContext\`, D3 best practices, efficiency, readability, visualization choice, aesthetics, and error handling based on your reviewer system prompt):`;

      // The user message to the coder for revision includes its original system prompt for context
      const createRevisionPrompt = (initialGenerationContent: string | null, reviewFromChatbot2: string | null): string => `
You are the AI assistant that generated D3.js code. Your previous work was reviewed by another AI.
Based on the review, please revise your D3.js code. Remember to use data from the \`dataContext\` variable.

Original User Request:
---
Selected data types for this query: ${selectedDataTypes?.join(', ') || 'Default (Game Data)'}. User's request: ${userQuery}
---
Original System Prompt You Followed:
---
${coderSystemPromptToUse}
---
Your Initial D3.js Code:
---
\`\`\`javascript
${extractCodeFromResponse(initialGenerationContent).code || "No initial code."}
\`\`\`
---
Review of Your Code (from Chatbot2):
---
${reviewFromChatbot2 || "No review feedback provided."}
---
Your Revised D3.js Code (only the JavaScript code block, ensure it uses \`dataContext\` correctly):`;
      
      const reviewCycleOutputs: AiReviewCycleRawOutputs = await performAiReviewCycle(
        chatbot1ModelToUse, 
        coderSystemMessage, 
        initialUserMessages, 
        chatbot2ModelToUse, 
        reviewerSystemMessage,
        createReviewerPrompt, 
        createRevisionPrompt
      );
      
      const { code: initialCode, message_text: initialMessageText } = extractCodeFromResponse(reviewCycleOutputs.chatbot1InitialResponse.content);
      const { code: revisedCode, message_text: revisedMessageText } = extractCodeFromResponse(reviewCycleOutputs.chatbot1RevisionResponse.content, "Code revised by Chatbot1.");

      if (!initialCode.trim() && !revisedCode.trim()) {
         finalApiResponse = {
            message: `Chatbot1 (Model: ${chatbot1ModelToUse}) did not produce code. Initial response: ${initialMessageText || reviewCycleOutputs.chatbot1InitialResponse.content}. Revision attempt also failed. Reviewer (Model: ${chatbot2ModelToUse}) said: ${reviewCycleOutputs.chatbot2ReviewResponse.content || "No review content."}`,
            code: "",
        };
      } else {
        finalApiResponse = {
          message: `Code generated with review. Initial response: "${initialMessageText}". Reviewer (Model: ${chatbot2ModelToUse}) said: "${reviewCycleOutputs.chatbot2ReviewResponse.content || "No review content."}". Final AI response: "${revisedMessageText}"`,
          code: revisedCode || initialCode,
        };
      }
    } else {
      if (!modelResolution.chatbot1Model) {
        console.error("DataLab API: Primary model not resolved properly for user", clerkUser.id);
        return NextResponse.json({ error: "Failed to resolve model.", dataContext: querySpecificDataContext }, { status: 500 });
      }
      const modelToUse = modelResolution.chatbot1Model;
      const messagesToAI: ChatCompletionMessageParam[] = [coderSystemMessage, ...initialUserMessages];
      const response = await callOpenAIChat(modelToUse, messagesToAI);
      const aiResponseContent = response.choices[0].message.content;
      const { code, message_text } = extractCodeFromResponse(aiResponseContent, "Generated D3.js visualization code.");
      finalApiResponse = { message: message_text, code: code };
    }

    finalApiResponse.dataContext = querySpecificDataContext;
    
    const incrementParams: IncrementApiUsageParams = {
        userId: clerkUser.id,
        isSubscribed: isSubscribed,
        useCodeReview: useCodeReview,
        coderModelId: modelResolution.chatbot1Model,
        reviewerModelId: useCodeReview ? modelResolution.chatbot2Model : null
    };
    await incrementApiUsage(incrementParams);

    const usageData = await prisma.apiUsage.findUnique({ where: { userId: clerkUser.id } });
    if (usageData) {
        finalApiResponse.remainingRequests = Math.max(0, (usageData.monthlyLimit) - (usageData.usageCount));
    } else {
        const limitForUser = getMonthlyLimitForTier(profile?.subscriptionTier);
        finalApiResponse.remainingRequests = limitForUser;
    }

    return NextResponse.json(finalApiResponse);

  } catch (error: any) {
    console.error("Error in DataLab chat:", error);
    const dataContextForError = (error as any).dataContext || null; 
    return NextResponse.json(
      { 
        error: "Failed to generate visualization", 
        details: error.message, 
        stack: error.stack,
        ...(dataContextForError && { dataContext: dataContextForError }) 
      }, 
      { status: 500 }
    );
  }
}